name: CI
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.0.0
      with:
        node-version: 16.13.2
    - name: Intalacao mocha e dos pacotes para teste
      run: |
        cd src;
        npm install -g mocha;
        npm install
