name: CI
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.13.2
      - name: Intalacao mocha e dos pacotes para teste
        run: |
          cd src;
          npm install -g mocha;
          npm install
      - name: Execucao testes
        run: mocha src/test/convert.js
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: '${{secrets.DOCKERHUB_USERNAME}}'
          password: '${{secrets.DOCKERHUB_PASSWORD}}'
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            talibarbosa/aula-conversao-temperatura:${{github.run_number}}
            talibarbosa/aula-conversao-temperatura:latest
